# Generated by Django 2.1.4 on 2018-12-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_mgr_app', '0001_initial'),
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_mgr_app.Product')),
            ],
        ),
    ]
