# Generated by Django 2.1.4 on 2018-12-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.CharField(default='', max_length=50, null=True)),
                ('fabric', models.CharField(default='', max_length=50, null=True)),
                ('shape', models.CharField(default='', max_length=50, null=True)),
                ('part', models.CharField(default='', max_length=50, null=True)),
                ('style', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img_url', models.CharField(max_length=256, null=True)),
                ('product_url', models.CharField(max_length=256)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('date', models.DateTimeField(verbose_name='rating date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_mgr_app.Product')),
            ],
        ),
    ]
