# Generated by Django 2.1.4 on 2018-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mgr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='rating date'),
        ),
    ]
